# Generated by Django 4.0.6 on 2022-08-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0008_productcontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontext',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productcontext',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productcontext',
            name='image2',
            field=models.TextField(blank=True),
        ),
    ]
