# Generated by Django 4.0.6 on 2022-08-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.BooleanField(null=True),
        ),
    ]
