# Generated by Django 4.0.6 on 2022-08-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('slug', models.SlugField(max_length=24)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=32),
        ),
    ]
