# Generated by Django 4.0.6 on 2022-08-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0007_product_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
                ('amount', models.IntegerField(null=True)),
                ('button', models.CharField(max_length=32)),
                ('basket', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=32)),
                ('availability', models.BooleanField(null=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='aplication.category')),
            ],
        ),
    ]
